name: Release Application

on:
  push:
    branches:
      - main        # or "master" or whatever your default branch is

env:
  REGISTRY: quay.io
  IMAGE_NAME: elias_dams/alm-workshop

jobs:
  deploy:
    if: github.ref == 'refs/heads/main'
    environment: development
    runs-on: ubuntu-22.04
    steps:
      - name: Checkout
        uses: actions/checkout@v2

      - name: Login OpenShift
        uses: redhat-actions/oc-login@v1
        with:
          openshift_server_url: ${{ secrets.OPENSHIFT_SERVER_URL }}
          openshift_token: ${{ secrets.OPENSHIFT_TOKEN }}
          namespace: ${{ secrets.OPENSHIFT_NAMESPACE }}

      - name: Apply Openshift YAML
        run: |
          # ADD YOUR COMMANDS HERE
